# ==========================================
# APPLICATION
# ==========================================
spring.application.name=HospitalManagementSystem

# Active Profile
spring.profiles.active=dev

# ==========================================
# SERVER
# ==========================================
server.port=8080

# ==========================================
# JSON
# ==========================================
spring.jackson.serialization.indent_output=true

# ==========================================
# FILE UPLOAD
# ==========================================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ==========================================
# JWT
# ==========================================
jwt.secret=ThisIsAVeryLongSecretKeyForJwtSigning1234567890
jwt.expiration=86400000

# ==========================================
# ERROR HANDLING
# ==========================================
server.error.include-message=always
server.error.include-binding-errors=always

# ==========================================
# LOGGING
# ==========================================
logging.level.org.springframework=INFO

# ==========================================
# ACTUATOR
# ==========================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ==========================================
# JACKSON
# ==========================================
spring.jackson.default-property-inclusion=non_null

# ==========================================
# BANNER
# ==========================================
spring.main.banner-mode=console