# ==========================================
# DATABASE
# ==========================================
spring.datasource.url=jdbc:mariadb://production-server:3306/hospital_db
spring.datasource.username=hospital_user
spring.datasource.password=StrongPassword
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# ==========================================
# JPA
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ==========================================
# LOGGING
# ==========================================
logging.level.root=WARN
logging.level.org.springframework=INFO
logging.level.org.springframework.security=WARN

# ==========================================
# ACTUATOR
# ==========================================
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never